<?php
$content = file_get_contents('c:\xampp\htdocs\jurnal\pages\guru\ekinerja.php');

$contextMenuHTML = <<<EOT
<!-- Context Menu Custom -->
<div id="customContextMenu" class="dropdown-menu shadow-sm" style="display:none; position:absolute; z-index:9999;">
    <a class="dropdown-item" href="#" id="ctxRename"><i class="bi bi-pencil-square text-primary me-2"></i> Rename</a>
    <a class="dropdown-item" href="#" id="ctxCopy"><i class="bi bi-copy text-success me-2"></i> Copy</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item text-danger" href="#" id="ctxDelete"><i class="bi bi-trash text-danger me-2"></i> Delete</a>
</div>

<script>
let currentCtxItem = null;

$(document).on('contextmenu', '.drive-item', function(e) {
    e.preventDefault();
    currentCtxItem = {
        id: $(this).data('id'),
        type: $(this).data('type'),
        name: $(this).data('name')
    };
    
    $('#customContextMenu').css({
        display: 'block',
        left: e.pageX,
        top: e.pageY
    });
});

$(document).on('click', function() {
    $('#customContextMenu').hide();
});

$('#ctxRename').on('click', function(e) {
    e.preventDefault();
    if(currentCtxItem) {
        let newName = prompt('Rename item:', currentCtxItem.name);
        if(newName && newName !== currentCtxItem.name) {
            $.post('?ajax=perangkat_rename_item', {id: currentCtxItem.id, nama_baru: newName}, function(res) {
                if(res.status === 'success') {
                    loadPerangkatDrive();
                } else {
                    alert('Gagal rename: ' + res.message);
                }
            }, 'json');
        }
    }
});

$('#ctxCopy').on('click', function(e) {
    e.preventDefault();
    if(currentCtxItem) {
        $.post('?ajax=perangkat_copy_item', {id: currentCtxItem.id}, function(res) {
            if(res.status === 'success') {
                loadPerangkatDrive();
            } else {
                alert('Gagal copy: ' + res.message);
            }
        }, 'json');
    }
});

$('#ctxDelete').on('click', function(e) {
    e.preventDefault();
    if(currentCtxItem) {
        if(currentCtxItem.type === 'folder') {
            deletePerangkatFolder(currentCtxItem.id, currentCtxItem.name);
        } else {
            deletePerangkatFile(currentCtxItem.id);
        }
    }
});
</script>
EOT;

$search = "</body>";
$content = str_replace($search, $contextMenuHTML . "\n" . $search, $content);

// Also we need to add `.drive-item` class and data-id, data-type, data-name to the HTML generated by loadPerangkatDrive.
// I will patch loadPerangkatDrive string inside ekinerja.php.

$searchLoadDrive = <<<EOT
                        <div class="col-12 mb-2">
                            <div class="card border rounded-3 p-3" style="background:#f8fafc;">
                                <div class="d-flex justify-content-between align-items-center mb-3 border-bottom pb-2">
EOT;
$replaceLoadDrive = <<<EOT
                        <div class="col-12 mb-2 drive-item" data-id="\${f.id}" data-type="folder" data-name="\${f.nama}">
                            <div class="card border rounded-3 p-3" style="background:#f8fafc;">
                                <div class="d-flex justify-content-between align-items-center mb-3 border-bottom pb-2">
EOT;
$content = str_replace($searchLoadDrive, $replaceLoadDrive, $content);


$searchFile = <<<EOT
                                <div class="col-md-4">
                                    <div class="card p-2 border rounded" style="background:#fff;">
EOT;
$replaceFile = <<<EOT
                                <div class="col-md-4">
                                    <div class="card p-2 border rounded drive-item" style="background:#fff; cursor:context-menu;" data-id="\${file.id}" data-type="file" data-name="\${file.nama_file}">
EOT;
$content = str_replace($searchFile, $replaceFile, $content);

file_put_contents('c:\xampp\htdocs\jurnal\pages\guru\ekinerja.php', $content);
echo "Context Menu logic patched in ekinerja.php";
?>
