<?php
// Simple web-based DB config writer
// WARNING: Delete this file after setup for security.

$info = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host = $_POST['host'] ?? 'localhost';
    $user = $_POST['user'] ?? 'root';
    $pass = $_POST['pass'] ?? '';
    $db   = $_POST['db'] ?? 'jurnal';

    // Test connection first
    mysqli_report(MYSQLI_REPORT_OFF);
    $link = @mysqli_connect($host, $user, $pass, $db);
    if (!$link) {
        $error = 'Gagal konek MySQL: ' . mysqli_connect_error();
    } else {
        // Build config.local.php content
        $cfg = "<?php\n" .
               "// Generated by setup-db.php on " . date('c') . "\n" .
               "// Override DB credentials for local environment\n" .
               "\$host = '" . addslashes($host) . "';\n" .
               "\$user = '" . addslashes($user) . "';\n" .
               "\$password = '" . addslashes($pass) . "';\n" .
               "\$db = '" . addslashes($db) . "';\n";
        $path = __DIR__ . DIRECTORY_SEPARATOR . 'config.local.php';
        if (@file_put_contents($path, $cfg) !== false) {
            $info = 'config.local.php berhasil dibuat. Anda bisa menutup halaman ini.';
            // optional: try redirect to db_test
            header('Location: db_test.php');
            exit;
        } else {
            $error = 'Gagal menulis config.local.php. Periksa izin folder.';
        }
        @mysqli_close($link);
    }
}

// Defaults for form
$defaultHost = 'localhost';
$defaultUser = 'root';
$defaultDb   = 'jurnal';
?>
<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Setup Koneksi Database</title>
  <link rel="stylesheet" href="css/bootstrap.min.css"/>
  <style>body{max-width:720px;margin:40px auto;padding:0 16px}</style>
</head>
<body>
  <h1>Setup Koneksi Database</h1>
  <p>Masukkan kredensial MySQL Anda, lalu klik Simpan. Setelah berhasil, <strong>hapus file setup-db.php</strong> demi keamanan.</p>
  <?php if ($error): ?>
    <div class="alert alert-danger" role="alert"><?php echo htmlspecialchars($error); ?></div>
  <?php endif; ?>
  <?php if ($info): ?>
    <div class="alert alert-success" role="alert"><?php echo htmlspecialchars($info); ?></div>
  <?php endif; ?>
  <form method="post">
    <div class="mb-3">
      <label class="form-label">Host</label>
      <input name="host" class="form-control" value="<?php echo htmlspecialchars($_POST['host'] ?? $defaultHost); ?>" required>
    </div>
    <div class="mb-3">
      <label class="form-label">User</label>
      <input name="user" class="form-control" value="<?php echo htmlspecialchars($_POST['user'] ?? $defaultUser); ?>" required>
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input name="pass" type="password" class="form-control" value="<?php echo htmlspecialchars($_POST['pass'] ?? ''); ?>">
    </div>
    <div class="mb-3">
      <label class="form-label">Database</label>
      <input name="db" class="form-control" value="<?php echo htmlspecialchars($_POST['db'] ?? $defaultDb); ?>" required>
    </div>
    <button type="submit" class="btn btn-primary">Simpan</button>
  </form>
</body>
</html>

