name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Sync Files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.sman1sumber.sch.id
        username: web2@sman1sumber.sch.id
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
